name: 'demo'
log_dir: 'output'
data_train_dir: 'data/data_train'
data_test_dir: 'data/data_test'
image_height: 224
image_width: 224

classes: 200
base_ch: 144
groups: 1
shuffle: true

learning_rate: 0.01
momentum: 0.9
weight_decay: 0.0005
batch_size: 32
epoch: 10
show_top_k: 5
